import os

PROJECT_PATH = os.getcwd()
DATA_PATH = "/home/matthieu/Dataset/SFCrimeClassification"

Header = ['Dates', 'Category', 'Descript', 'DayOfWeek', 'PdDistrict', 'Resolution', 'Address', 'X', 'Y']

Category = ['WARRANTS','OTHER OFFENSES','LARCENY/THEFT','VEHICLE THEFT','VANDALISM'
 'NON-CRIMINAL','ROBBERY','ASSAULT','WEAPON LAWS','BURGLARY'
 'SUSPICIOUS OCC','DRUNKENNESS','FORGERY/COUNTERFEITING','DRUG/NARCOTIC'
 'STOLEN PROPERTY','SECONDARY CODES','TRESPASS','MISSING PERSON','FRAUD'
 'KIDNAPPING','RUNAWAY','DRIVING UNDER THE INFLUENCE'
 'SEX OFFENSES FORCIBLE','PROSTITUTION','DISORDERLY CONDUCT','ARSON'
 'FAMILY OFFENSES','LIQUOR LAWS','BRIBERY','EMBEZZLEMENT','SUICIDE'
 'LOITERING','SEX OFFENSES NON FORCIBLE','EXTORTION','GAMBLING'
 'BAD CHECKS','TREA','RECOVERED VEHICLE','PORNOGRAPHY/OBSCENE MAT']

PdDistrict = ['NORTHERN','PARK','INGLESIDE','BAYVIEW','RICHMOND','CENTRAL','TARAVAL'
 'TENDERLOIN','MISSION','SOUTHERN']
